name: Weekly GBP OIS Report

on:
  schedule:
    # Runs every Monday at 8:00 AM UTC
    - cron: "0 8 * * 1"
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.0"

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          install.packages(c(
            'tidyverse',
            'readxl', 
            'lubridate',
            'xts',
            'showtext',
            'here',
            'knitr',
            'quarto'
          ))
        shell: Rscript {0}

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto document
        run: |
          quarto render report/01_report.qmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gbp-ois-report
          path: report/01_report.pdf

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add report/01_report.pdf
          git diff --staged --quiet || git commit -m "Auto-update: Weekly GBP OIS Report $(date +'%Y-%m-%d')"
          git push
